//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillionBank.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignIn", ReplyAction="*")]
        BillionBank.ServiceReference1.SignInResponse SignIn(BillionBank.ServiceReference1.SignInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignIn", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBank.ServiceReference1.SignInResponse> SignInAsync(BillionBank.ServiceReference1.SignInRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignIn", Namespace="http://tempuri.org/", Order=0)]
        public BillionBank.ServiceReference1.SignInRequestBody Body;
        
        public SignInRequest() {
        }
        
        public SignInRequest(BillionBank.ServiceReference1.SignInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string prefferedName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string add1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string add2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string add3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string psswd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string question;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string answer;
        
        public SignInRequestBody() {
        }
        
        public SignInRequestBody(string email, string ID, string name, string prefferedName, string add1, string add2, string add3, string number, string psswd, string question, string answer) {
            this.email = email;
            this.ID = ID;
            this.name = name;
            this.prefferedName = prefferedName;
            this.add1 = add1;
            this.add2 = add2;
            this.add3 = add3;
            this.number = number;
            this.psswd = psswd;
            this.question = question;
            this.answer = answer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignInResponse", Namespace="http://tempuri.org/", Order=0)]
        public BillionBank.ServiceReference1.SignInResponseBody Body;
        
        public SignInResponse() {
        }
        
        public SignInResponse(BillionBank.ServiceReference1.SignInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SignInResult;
        
        public SignInResponseBody() {
        }
        
        public SignInResponseBody(bool SignInResult) {
            this.SignInResult = SignInResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : BillionBank.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<BillionBank.ServiceReference1.WebService1Soap>, BillionBank.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBank.ServiceReference1.SignInResponse BillionBank.ServiceReference1.WebService1Soap.SignIn(BillionBank.ServiceReference1.SignInRequest request) {
            return base.Channel.SignIn(request);
        }
        
        public bool SignIn(string email, string ID, string name, string prefferedName, string add1, string add2, string add3, string number, string psswd, string question, string answer) {
            BillionBank.ServiceReference1.SignInRequest inValue = new BillionBank.ServiceReference1.SignInRequest();
            inValue.Body = new BillionBank.ServiceReference1.SignInRequestBody();
            inValue.Body.email = email;
            inValue.Body.ID = ID;
            inValue.Body.name = name;
            inValue.Body.prefferedName = prefferedName;
            inValue.Body.add1 = add1;
            inValue.Body.add2 = add2;
            inValue.Body.add3 = add3;
            inValue.Body.number = number;
            inValue.Body.psswd = psswd;
            inValue.Body.question = question;
            inValue.Body.answer = answer;
            BillionBank.ServiceReference1.SignInResponse retVal = ((BillionBank.ServiceReference1.WebService1Soap)(this)).SignIn(inValue);
            return retVal.Body.SignInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBank.ServiceReference1.SignInResponse> BillionBank.ServiceReference1.WebService1Soap.SignInAsync(BillionBank.ServiceReference1.SignInRequest request) {
            return base.Channel.SignInAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBank.ServiceReference1.SignInResponse> SignInAsync(string email, string ID, string name, string prefferedName, string add1, string add2, string add3, string number, string psswd, string question, string answer) {
            BillionBank.ServiceReference1.SignInRequest inValue = new BillionBank.ServiceReference1.SignInRequest();
            inValue.Body = new BillionBank.ServiceReference1.SignInRequestBody();
            inValue.Body.email = email;
            inValue.Body.ID = ID;
            inValue.Body.name = name;
            inValue.Body.prefferedName = prefferedName;
            inValue.Body.add1 = add1;
            inValue.Body.add2 = add2;
            inValue.Body.add3 = add3;
            inValue.Body.number = number;
            inValue.Body.psswd = psswd;
            inValue.Body.question = question;
            inValue.Body.answer = answer;
            return ((BillionBank.ServiceReference1.WebService1Soap)(this)).SignInAsync(inValue);
        }
    }
}
