//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BillionBank.BilliService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BilliService.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccInfo", ReplyAction="*")]
        BillionBank.BilliService.AccInfoResponse AccInfo(BillionBank.BilliService.AccInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AccInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBank.BilliService.AccInfoResponse> AccInfoAsync(BillionBank.BilliService.AccInfoRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerInfo", ReplyAction="*")]
        BillionBank.BilliService.CustomerInfoResponse CustomerInfo(BillionBank.BilliService.CustomerInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CustomerInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBank.BilliService.CustomerInfoResponse> CustomerInfoAsync(BillionBank.BilliService.CustomerInfoRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignIn", ReplyAction="*")]
        BillionBank.BilliService.SignInResponse SignIn(BillionBank.BilliService.SignInRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SignIn", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBank.BilliService.SignInResponse> SignInAsync(BillionBank.BilliService.SignInRequest request);
        
        // CODEGEN: Generating message contract since element name amount from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Transactions", ReplyAction="*")]
        BillionBank.BilliService.TransactionsResponse Transactions(BillionBank.BilliService.TransactionsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Transactions", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBank.BilliService.TransactionsResponse> TransactionsAsync(BillionBank.BilliService.TransactionsRequest request);
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pay", ReplyAction="*")]
        BillionBank.BilliService.PayResponse Pay(BillionBank.BilliService.PayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Pay", ReplyAction="*")]
        System.Threading.Tasks.Task<BillionBank.BilliService.PayResponse> PayAsync(BillionBank.BilliService.PayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccInfo", Namespace="http://tempuri.org/", Order=0)]
        public BillionBank.BilliService.AccInfoRequestBody Body;
        
        public AccInfoRequest() {
        }
        
        public AccInfoRequest(BillionBank.BilliService.AccInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string accName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dropdwn;
        
        public AccInfoRequestBody() {
        }
        
        public AccInfoRequestBody(string email, string accName, string dropdwn) {
            this.email = email;
            this.accName = accName;
            this.dropdwn = dropdwn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AccInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AccInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public BillionBank.BilliService.AccInfoResponseBody Body;
        
        public AccInfoResponse() {
        }
        
        public AccInfoResponse(BillionBank.BilliService.AccInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AccInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AccInfoResult;
        
        public AccInfoResponseBody() {
        }
        
        public AccInfoResponseBody(bool AccInfoResult) {
            this.AccInfoResult = AccInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerInfo", Namespace="http://tempuri.org/", Order=0)]
        public BillionBank.BilliService.CustomerInfoRequestBody Body;
        
        public CustomerInfoRequest() {
        }
        
        public CustomerInfoRequest(BillionBank.BilliService.CustomerInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string add1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string add2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email;
        
        public CustomerInfoRequestBody() {
        }
        
        public CustomerInfoRequestBody(string name, string add1, string add2, string city, string no, string email) {
            this.name = name;
            this.add1 = add1;
            this.add2 = add2;
            this.city = city;
            this.no = no;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CustomerInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CustomerInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public BillionBank.BilliService.CustomerInfoResponseBody Body;
        
        public CustomerInfoResponse() {
        }
        
        public CustomerInfoResponse(BillionBank.BilliService.CustomerInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CustomerInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CustomerInfoResult;
        
        public CustomerInfoResponseBody() {
        }
        
        public CustomerInfoResponseBody(bool CustomerInfoResult) {
            this.CustomerInfoResult = CustomerInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignIn", Namespace="http://tempuri.org/", Order=0)]
        public BillionBank.BilliService.SignInRequestBody Body;
        
        public SignInRequest() {
        }
        
        public SignInRequest(BillionBank.BilliService.SignInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string prefferedName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string add1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string add2;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string add3;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string number;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string psswd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string question;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string answer;
        
        public SignInRequestBody() {
        }
        
        public SignInRequestBody(string email, string ID, string name, string prefferedName, string add1, string add2, string add3, string number, string psswd, string question, string answer) {
            this.email = email;
            this.ID = ID;
            this.name = name;
            this.prefferedName = prefferedName;
            this.add1 = add1;
            this.add2 = add2;
            this.add3 = add3;
            this.number = number;
            this.psswd = psswd;
            this.question = question;
            this.answer = answer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SignInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SignInResponse", Namespace="http://tempuri.org/", Order=0)]
        public BillionBank.BilliService.SignInResponseBody Body;
        
        public SignInResponse() {
        }
        
        public SignInResponse(BillionBank.BilliService.SignInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SignInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SignInResult;
        
        public SignInResponseBody() {
        }
        
        public SignInResponseBody(bool SignInResult) {
            this.SignInResult = SignInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransactionsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Transactions", Namespace="http://tempuri.org/", Order=0)]
        public BillionBank.BilliService.TransactionsRequestBody Body;
        
        public TransactionsRequest() {
        }
        
        public TransactionsRequest(BillionBank.BilliService.TransactionsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TransactionsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string reff;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string repRef;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string dropdownFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string dropdownTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email;
        
        public TransactionsRequestBody() {
        }
        
        public TransactionsRequestBody(string amount, string reff, string repRef, string dropdownFrom, string dropdownTo, string email) {
            this.amount = amount;
            this.reff = reff;
            this.repRef = repRef;
            this.dropdownFrom = dropdownFrom;
            this.dropdownTo = dropdownTo;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TransactionsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TransactionsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BillionBank.BilliService.TransactionsResponseBody Body;
        
        public TransactionsResponse() {
        }
        
        public TransactionsResponse(BillionBank.BilliService.TransactionsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TransactionsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool TransactionsResult;
        
        public TransactionsResponseBody() {
        }
        
        public TransactionsResponseBody(bool TransactionsResult) {
            this.TransactionsResult = TransactionsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Pay", Namespace="http://tempuri.org/", Order=0)]
        public BillionBank.BilliService.PayRequestBody Body;
        
        public PayRequest() {
        }
        
        public PayRequest(BillionBank.BilliService.PayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string dropdwn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string amt;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string accNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string reff;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string repRef;
        
        public PayRequestBody() {
        }
        
        public PayRequestBody(string email, string dropdwn, string amt, string accNo, string reff, string repRef) {
            this.email = email;
            this.dropdwn = dropdwn;
            this.amt = amt;
            this.accNo = accNo;
            this.reff = reff;
            this.repRef = repRef;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PayResponse", Namespace="http://tempuri.org/", Order=0)]
        public BillionBank.BilliService.PayResponseBody Body;
        
        public PayResponse() {
        }
        
        public PayResponse(BillionBank.BilliService.PayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class PayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PayResult;
        
        public PayResponseBody() {
        }
        
        public PayResponseBody(string PayResult) {
            this.PayResult = PayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : BillionBank.BilliService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<BillionBank.BilliService.WebService1Soap>, BillionBank.BilliService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBank.BilliService.AccInfoResponse BillionBank.BilliService.WebService1Soap.AccInfo(BillionBank.BilliService.AccInfoRequest request) {
            return base.Channel.AccInfo(request);
        }
        
        public bool AccInfo(string email, string accName, string dropdwn) {
            BillionBank.BilliService.AccInfoRequest inValue = new BillionBank.BilliService.AccInfoRequest();
            inValue.Body = new BillionBank.BilliService.AccInfoRequestBody();
            inValue.Body.email = email;
            inValue.Body.accName = accName;
            inValue.Body.dropdwn = dropdwn;
            BillionBank.BilliService.AccInfoResponse retVal = ((BillionBank.BilliService.WebService1Soap)(this)).AccInfo(inValue);
            return retVal.Body.AccInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBank.BilliService.AccInfoResponse> BillionBank.BilliService.WebService1Soap.AccInfoAsync(BillionBank.BilliService.AccInfoRequest request) {
            return base.Channel.AccInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBank.BilliService.AccInfoResponse> AccInfoAsync(string email, string accName, string dropdwn) {
            BillionBank.BilliService.AccInfoRequest inValue = new BillionBank.BilliService.AccInfoRequest();
            inValue.Body = new BillionBank.BilliService.AccInfoRequestBody();
            inValue.Body.email = email;
            inValue.Body.accName = accName;
            inValue.Body.dropdwn = dropdwn;
            return ((BillionBank.BilliService.WebService1Soap)(this)).AccInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBank.BilliService.CustomerInfoResponse BillionBank.BilliService.WebService1Soap.CustomerInfo(BillionBank.BilliService.CustomerInfoRequest request) {
            return base.Channel.CustomerInfo(request);
        }
        
        public bool CustomerInfo(string name, string add1, string add2, string city, string no, string email) {
            BillionBank.BilliService.CustomerInfoRequest inValue = new BillionBank.BilliService.CustomerInfoRequest();
            inValue.Body = new BillionBank.BilliService.CustomerInfoRequestBody();
            inValue.Body.name = name;
            inValue.Body.add1 = add1;
            inValue.Body.add2 = add2;
            inValue.Body.city = city;
            inValue.Body.no = no;
            inValue.Body.email = email;
            BillionBank.BilliService.CustomerInfoResponse retVal = ((BillionBank.BilliService.WebService1Soap)(this)).CustomerInfo(inValue);
            return retVal.Body.CustomerInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBank.BilliService.CustomerInfoResponse> BillionBank.BilliService.WebService1Soap.CustomerInfoAsync(BillionBank.BilliService.CustomerInfoRequest request) {
            return base.Channel.CustomerInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBank.BilliService.CustomerInfoResponse> CustomerInfoAsync(string name, string add1, string add2, string city, string no, string email) {
            BillionBank.BilliService.CustomerInfoRequest inValue = new BillionBank.BilliService.CustomerInfoRequest();
            inValue.Body = new BillionBank.BilliService.CustomerInfoRequestBody();
            inValue.Body.name = name;
            inValue.Body.add1 = add1;
            inValue.Body.add2 = add2;
            inValue.Body.city = city;
            inValue.Body.no = no;
            inValue.Body.email = email;
            return ((BillionBank.BilliService.WebService1Soap)(this)).CustomerInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBank.BilliService.SignInResponse BillionBank.BilliService.WebService1Soap.SignIn(BillionBank.BilliService.SignInRequest request) {
            return base.Channel.SignIn(request);
        }
        
        public bool SignIn(string email, string ID, string name, string prefferedName, string add1, string add2, string add3, string number, string psswd, string question, string answer) {
            BillionBank.BilliService.SignInRequest inValue = new BillionBank.BilliService.SignInRequest();
            inValue.Body = new BillionBank.BilliService.SignInRequestBody();
            inValue.Body.email = email;
            inValue.Body.ID = ID;
            inValue.Body.name = name;
            inValue.Body.prefferedName = prefferedName;
            inValue.Body.add1 = add1;
            inValue.Body.add2 = add2;
            inValue.Body.add3 = add3;
            inValue.Body.number = number;
            inValue.Body.psswd = psswd;
            inValue.Body.question = question;
            inValue.Body.answer = answer;
            BillionBank.BilliService.SignInResponse retVal = ((BillionBank.BilliService.WebService1Soap)(this)).SignIn(inValue);
            return retVal.Body.SignInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBank.BilliService.SignInResponse> BillionBank.BilliService.WebService1Soap.SignInAsync(BillionBank.BilliService.SignInRequest request) {
            return base.Channel.SignInAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBank.BilliService.SignInResponse> SignInAsync(string email, string ID, string name, string prefferedName, string add1, string add2, string add3, string number, string psswd, string question, string answer) {
            BillionBank.BilliService.SignInRequest inValue = new BillionBank.BilliService.SignInRequest();
            inValue.Body = new BillionBank.BilliService.SignInRequestBody();
            inValue.Body.email = email;
            inValue.Body.ID = ID;
            inValue.Body.name = name;
            inValue.Body.prefferedName = prefferedName;
            inValue.Body.add1 = add1;
            inValue.Body.add2 = add2;
            inValue.Body.add3 = add3;
            inValue.Body.number = number;
            inValue.Body.psswd = psswd;
            inValue.Body.question = question;
            inValue.Body.answer = answer;
            return ((BillionBank.BilliService.WebService1Soap)(this)).SignInAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBank.BilliService.TransactionsResponse BillionBank.BilliService.WebService1Soap.Transactions(BillionBank.BilliService.TransactionsRequest request) {
            return base.Channel.Transactions(request);
        }
        
        public bool Transactions(string amount, string reff, string repRef, string dropdownFrom, string dropdownTo, string email) {
            BillionBank.BilliService.TransactionsRequest inValue = new BillionBank.BilliService.TransactionsRequest();
            inValue.Body = new BillionBank.BilliService.TransactionsRequestBody();
            inValue.Body.amount = amount;
            inValue.Body.reff = reff;
            inValue.Body.repRef = repRef;
            inValue.Body.dropdownFrom = dropdownFrom;
            inValue.Body.dropdownTo = dropdownTo;
            inValue.Body.email = email;
            BillionBank.BilliService.TransactionsResponse retVal = ((BillionBank.BilliService.WebService1Soap)(this)).Transactions(inValue);
            return retVal.Body.TransactionsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBank.BilliService.TransactionsResponse> BillionBank.BilliService.WebService1Soap.TransactionsAsync(BillionBank.BilliService.TransactionsRequest request) {
            return base.Channel.TransactionsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBank.BilliService.TransactionsResponse> TransactionsAsync(string amount, string reff, string repRef, string dropdownFrom, string dropdownTo, string email) {
            BillionBank.BilliService.TransactionsRequest inValue = new BillionBank.BilliService.TransactionsRequest();
            inValue.Body = new BillionBank.BilliService.TransactionsRequestBody();
            inValue.Body.amount = amount;
            inValue.Body.reff = reff;
            inValue.Body.repRef = repRef;
            inValue.Body.dropdownFrom = dropdownFrom;
            inValue.Body.dropdownTo = dropdownTo;
            inValue.Body.email = email;
            return ((BillionBank.BilliService.WebService1Soap)(this)).TransactionsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BillionBank.BilliService.PayResponse BillionBank.BilliService.WebService1Soap.Pay(BillionBank.BilliService.PayRequest request) {
            return base.Channel.Pay(request);
        }
        
        public string Pay(string email, string dropdwn, string amt, string accNo, string reff, string repRef) {
            BillionBank.BilliService.PayRequest inValue = new BillionBank.BilliService.PayRequest();
            inValue.Body = new BillionBank.BilliService.PayRequestBody();
            inValue.Body.email = email;
            inValue.Body.dropdwn = dropdwn;
            inValue.Body.amt = amt;
            inValue.Body.accNo = accNo;
            inValue.Body.reff = reff;
            inValue.Body.repRef = repRef;
            BillionBank.BilliService.PayResponse retVal = ((BillionBank.BilliService.WebService1Soap)(this)).Pay(inValue);
            return retVal.Body.PayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BillionBank.BilliService.PayResponse> BillionBank.BilliService.WebService1Soap.PayAsync(BillionBank.BilliService.PayRequest request) {
            return base.Channel.PayAsync(request);
        }
        
        public System.Threading.Tasks.Task<BillionBank.BilliService.PayResponse> PayAsync(string email, string dropdwn, string amt, string accNo, string reff, string repRef) {
            BillionBank.BilliService.PayRequest inValue = new BillionBank.BilliService.PayRequest();
            inValue.Body = new BillionBank.BilliService.PayRequestBody();
            inValue.Body.email = email;
            inValue.Body.dropdwn = dropdwn;
            inValue.Body.amt = amt;
            inValue.Body.accNo = accNo;
            inValue.Body.reff = reff;
            inValue.Body.repRef = repRef;
            return ((BillionBank.BilliService.WebService1Soap)(this)).PayAsync(inValue);
        }
    }
}
